name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Get release version
        run: echo "RELEASE_VERSION=$(poetry version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Build and publish Python package
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
